export const types = {
    SET_ME:"SET_ME",
    LOG_OUT:"LOG_OUT",
    FET_USER:"FET_USER",
    FET_PROJECT:"FET_PROJECT",
    DETAIL_PROJECT:"DETAIL_PROJECT",
    GET_CATEGORY:"GET_CATEGORY",
    FET_USER_SEARCH:"FET_USER_SEARCH",
    DELETE_PROJECT:"DELETE_PROJECT",
    UPDATE_PROJECT:"UPDATE_PROJECT",
    FETUSER_PROJECT:"FETUSER_PROJECT",
    GET_COMMENT:"GET_COMMENT",
    GET_ALL_PROJECT:"GET_ALL_PROJECT",
    GET_DETAIL_PROJECT:"GET_DETAIL_PROJECT",
    GET_ALL_STATUS:"GET_ALL_STATUS",
    GET_ALL_PRIORITY:"GET_ALL_PRIORITY",
    GET_ALL_TASKTYPE:"GET_ALL_TASKTYPE",
    GET_ALL_ASSIGNEES:"GET_ALL_ASSIGNEES",
    GET_TASK_DETAIL:"GET_TASK_DETAIL",
}

export const cybersoftKey = {
    HH_key : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCAwOSIsIkhldEhhblN0cmluZyI6IjI3LzAxLzIwMjIiLCJIZXRIYW5UaW1lIjoiMTY0MzI0MTYwMDAwMCIsIm5iZiI6MTYxNjM0NjAwMCwiZXhwIjoxNjQzMzg5MjAwfQ.NEQRF8SKORq7R7kYbYCCO9ZZXYxTWlbaTc2wxXWMfiw",
    PM_key:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCAwOSIsIkhldEhhblN0cmluZyI6IjI3LzAxLzIwMjIiLCJIZXRIYW5UaW1lIjoiMTY0MzI0MTYwMDAwMCIsIm5iZiI6MTYxNjM0NjAwMCwiZXhwIjoxNjQzMzg5MjAwfQ.NEQRF8SKORq7R7kYbYCCO9ZZXYxTWlbaTc2wxXWMfiw"
}